name: ESLint
run-name: ${{ github.actor }} pushed to ${{ github.ref }} running ESLint
on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
    paths:
      - '**.js'
      - '**.jsx'
      - '**.ts'
      - '**.tsx'

jobs:
  es-lint:
    name: Run ESLint scanning
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 'latest'
          cache: 'npm'

      - name: Install ESLint & Dependencies
        run: |
          npm install eslint@latest eslint-config-standard@latest
          npm install @microsoft/eslint-formatter-sarif@latest

      - name: Run ESLint
        run: npx eslint ./js/*
          --ext .js,.jsx,.ts,.tsx
          --config .eslintrc.js
          --format @microsoft/eslint-formatter-sarif
          --output-file eslint-results.sarif
        continue-on-error: true

      - name: Upload analysis results to Github
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: eslint-results.sarif
          wait-for-processing: true
